name: SwiftUISampleWithXcodeGen

options:
  bundleIdPrefix: com.macneko
  deploymentTarget: 
    iOS: 15.0
  xcodeVersion: "13.1"

settings:
  base:
    DEVELOPMENT_TEAM: 2FZSDA66L9
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CLANG_CXX_LANGUAGE_STANDARD: gnu++17
    CODE_SIGN_STYLE: Automatic

targets:
  SwiftUISampleWithXcodeGen:
    type: application
    platform: iOS
    sources: 
      - SwiftUISampleWithXcodeGen
    settings:
      base:
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"SwiftUISampleWithXcodeGen/Preview Content\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: SwiftUISampleWithXcodeGen/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]

  SwiftUISampleWithXcodeGenTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - SwiftUISampleWithXcodeGenTests
    dependencies:
      - target: SwiftUISampleWithXcodeGen
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    info:
      path: SwiftUISampleWithXcodeGenTests/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)

  SwiftUISampleWithXcodeGenUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: 
      - SwiftUISampleWithXcodeGenUITests
    dependencies:
      - target: SwiftUISampleWithXcodeGen
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    info:
      path: SwiftUISampleWithXcodeGenUITests/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
